### ISSUE TITLE
Throw more detailed Exception

### ISSUE THREAD

**Issue by Odonno** [uwp-squad/gitter-api-pcl#10]
Like in http://www.asp.net/web-api/overview/error-handling/exception-handling, we could handle errors by throwing detailed `HttpResponseException` instead of common `Exception`.

Thanks @gep13, an idea from #5

**Comment by gep13** [comment]
If that is the route that you want to go down, you might want to look at this:

https://github.com/octokit/octokit.net/blob/1266ac0f3a366f033061d0c1cc0785bc3c9f5bd3/Octokit/Models/Response/ApiError.cs

Which is how the guys who create Octokit, the .Net API for GitHub do things.

**Comment by Odonno** [comment]
Well, good idea in complement of the `ApiException` (https://github.com/octokit/octokit.net/blob/1266ac0f3a366f033061d0c1cc0785bc3c9f5bd3/Octokit/Exceptions/ApiException.cs).

**Comment by gep13** [comment]
:+1:
