### ISSUE TITLE
Is it possible to use conditional compilation to refactor services ?

### ISSUE THREAD

**Issue by Odonno** [uwp-squad/gitter-api-pcl#12]
@gep13 I had no other way to copy/paste a lot of code in front end, mainly because there is a different implementation of HttpClient in every front end projects.

But, since it is > 95% the same code, do you think we can put the code on PCL projects by using conditional compilation, `#if` ?

As PCL does not contains any conditional compilation symbol, I thought there was no other, but maybe not. Any idea ?

**Comment by gep13** [comment]
Can you not put all the Methods that use the HttpClient into a PCL, and reference that in each of the front end projects?  That way, you would be using a common HttpClient that they all understand.

**Comment by Odonno** [comment]
I'll take a look at octokit.net to see how they're doing conditional compilation, maybe they have a perfect solution.

**Comment by Odonno** [comment]
I see how they're doing. They are making linked files with `#if` conditional compilation inside each front project.

**Comment by Odonno** [comment]
Here it is. I have created linked files like in octokit, and so, there no need of copy/paste anymore. Just update a file in one of the front project, and it will be used by any of these.

You need to take of `#if` of course.

You can take a look at the new version.
