### ISSUE TITLE
How do I know if there was an error sending a message ?

### ISSUE THREAD

**Issue by gep13** [uwp-squad/gitter-api-pcl#5]
I am just looking at using the Gitter# library in my Cake.Gitter Addin, and I was just wondering...

When calling `IGitterApiService.SendMessageAsync` how do I get information back about any failures in sending the message?

**Comment by gep13** [comment]
Same question for the posting to the WebHook.  In the JSON response, when there is an error, it contains some text about what went wrong.  I think it would be good for the Gitter# API to return this information to consumers of the API.  What do you think?

**Comment by Odonno** [comment]
Well, I do not have any pattern on that.

The only thing I have is throwing an error (like timeout, server unreached, etc..). But, clearly, not the best way.

**Comment by gep13** [comment]
How are you handling that in Modern.Gitter?  Or are you not returning any specific error messages?  But rather generic error messges?

**Comment by Odonno** [comment]
I did not really care about error handling, so yes, nothing is really done for that.

If you have any idea of how to improve the API with error handling, you can.
Another thing, I could also go for a reactive version of the package, what do you think ? Rx supports error handling easily.

**Comment by gep13** [comment]
For my purposes, the inclusion of Rx I don't think would really help, as I am only really interested in one time message posts, not in continually using it.  I need to Post a message, get the result, and return, nothing else.

I think you would need to return another type from the API, that included additional properties, like Error.  If Error != null, then you would know that there was a problem, and you could inspect it for the issue.  If Error == null, then attempt to read the response.  I think this is a fairly common pattern.

**Comment by Odonno** [comment]
Rx is another concept, but you of course can use for a one time usage, like here to post a message. It may your code design, but it's as useful as common concept.

**Comment by Odonno** [comment]
About your Error design for the API, I don't see hat you want. You want me to add a return type to each method ? But .NET does not allow me to that. I'll check for design guidelines in the web, but don't know better than thowing an Exception at this time.

**Comment by gep13** [comment]
I guess I was thinking about something like this, which would be the response from the calls to your API:

```
    public class ApiOperation<T>
    {
        public ApiOperationStatus Status { get; set; }

        public T Result { get; set; }   
    }
```

Where ApiOperationStatus is an enumeration.  Consumers of your Api could then inspect the Status of the response, and if this isn't `Success` then they know something went wrong.  You could also include additional properties, like Error, which is a string, or Exception object, depending on how far you want to take it.  That way, the response from your API methods calls aren't exceptions, that additionally need to be caught and dealt with (which we wouldn't be able to deal with anyway) but rather, something that can be interrogated, and acted on.  It's just a thought.

**Comment by Odonno** [comment]
Ok, so, let's imagine some methods we have inside the package, users ill have to use something like : 

```
Task<ApiOperation<IEnumerable<Message>>> RetrieveMessages(...);
```

Don't you think it's too much ?

**Comment by gep13** [comment]
I really depends on how far you want to take it.  For something like RetrieveMessages, this is likely to be an empty list, and there might not be any other information that you can provide to the user.  However, when actually doing something, like PostMessage, JoinRoom, etc, there is likely additional information that you can provide.

**Comment by Odonno** [comment]
Well, at this time, I want to stay with an easy API usage, simple and strongly typed response.

You proposition seems great too. It's difficult to choose. :)

**Comment by Odonno** [comment]
So @gep13, does the API error handling works for you on your Cake.Gitter project ?

**Comment by gep13** [comment]
Not had a chance to play with this yet, but I will.

**Comment by Odonno** [comment]
Thinking about your `ApiOperation`, looks like Command pattern : http://www.dofactory.com/net/command-design-pattern

Here is an example of both design and implementation of a Command named `ApiOperation` : 

```
public class ApiOperation<T>
{
    // Mandatory properties/methods
    T Result { get; }
    Task ExecuteAsync(); // In this case, you'll make this method abstract

    // Optional properties/methods
    Exception Exception { get; }
    int StatusCode { get; }
    bool OperationState { get; }
}
```

Eventually, you can add the action executed by the `ExecuteAsync` method.

```
public class ApiOperation<T>
{
    // ...

     Action Action { get; set; }

     // ...
}
```

```
public class GitterApiService
{
    public ApiOperation<Message> RetrieveMessage(...)
    {
        return new ApiOperation<Message>
            {
                ...
            };
    }
}
```

```
// Use like that
var operation = new GitterApiService().RetrieveMessage();
await operation.ExecuteAsync();

// Here is the result
var result = operation.Result;
```

**Comment by Odonno** [comment]
@gep13  Is it still under discussion ?

I made changes in the Reactive implementation, so if you use Reactive, you can use the `OnError` handler to manage potentiel Exceptions in your code.

In the case of the "usual" implementation, I have found no other way than to write a try/catch. Still, it could be improved if you see something I don't.
