### ISSUE TITLE
System.Exception was thrown on webhook

### ISSUE THREAD

**Issue by gep13** [uwp-squad/gitter-api-pcl#7]
Any ideas on why I am getting this:

![image](https://cloud.githubusercontent.com/assets/1271146/10772758/79569d08-7cef-11e5-9862-07310d045a87.png)

The message is successfully posted to the Webhook, but I get an exception when trying to get the Result back.

Any ideas?

**Comment by Odonno** [comment]
Yep, I've worked with API principles, though, like having a returned status code.

```
if (!response.IsSuccessStatusCode)
    throw new Exception();
```

I'll remove this part and it will work as expected.

**Comment by Odonno** [comment]
Could you test with the new version 0.4.2 ? https://www.nuget.org/packages/gitter-api-pcl

**Comment by gep13** [comment]
Will do, thanks!

**Comment by gep13** [comment]
I have just upgraded to 0.4.2 and I am no longer getting the exception, however, I am always getting a false returned, when the message did actually post to my webhook url:

![image](https://cloud.githubusercontent.com/assets/1271146/10788645/c036b56a-7d70-11e5-8109-72795cd5ce0b.png)

![image](https://cloud.githubusercontent.com/assets/1271146/10788651/cdd140fa-7d70-11e5-8a44-8dd84ffc2c66.png)

any ideas on what I am doing wrong here?

**Comment by Odonno** [comment]
Hum, I will need to test the exact returned response. For now, I am doing that : 

```
return result == "ok";
```

But, I never used webhook, so maybe it's not the right response, could you try the code ? You can use LinqPad and see the response with your own parameters.

**Comment by gep13** [comment]
ok, so this is part of the issue:

![image](https://cloud.githubusercontent.com/assets/1271146/10789246/1b774874-7d74-11e5-9a2e-c7ed8ca27836.png)

Will keep doing some digging....

**Comment by Odonno** [comment]
Ok, maybe a good time to start with Integration Tests, at least with a fake room.

**Comment by gep13** [comment]
That's sounds like a plan to me.

I believe I have found the issue, I will work on implementing a fix, and I will submit a PR.

**Comment by Odonno** [comment]
Nice !

**Comment by Odonno** [comment]
Just in case, have you checked the returned status code ? It could help.

**Comment by gep13** [comment]
What version of Xamarin do you have installed?  I noticed that when I opened the solution, it made the following change:

![image](https://cloud.githubusercontent.com/assets/1271146/10803394/d94c08e0-7db9-11e5-909b-ad9ca28a4b18.png)

**Comment by Odonno** [comment]
Xamarin - 3.11.816.0
Xamarin.Android - 5.1.5.2

Don't know where it comes from.
